### ISSUE TITLE
incorrect master size

### ISSUE THREAD

**Issue by addy419** [phenax/bsp-layout#35]
bspwm 0.9.10
bsp-layout 10-05-2021 commit

bspwmrc:
```
#!/nix/store/xvvgw9sb8wk6d2c0j3ybn7sll67s3s4z-bash-4.4-p23/bin/bash
bspc monitor Virtual1 -d 1 2 3 4 5 6 7 8 9
bspc config active_border_color '#bd93f9'
bspc config border_width 1
bspc config borderless_monocle true
bspc config focused_border_color '#ff79c6'
bspc config gapless_monocle true
bspc config normal_border_color '#44475a'
bspc config presel_feedback_color '#6272a4'
bspc config split_ratio 0.500000
bspc config window_gap 12
bspc rule -a Emacs state='tiled'
# java gui fixes
export _JAVA_AWT_WM_NONREPARENTING=1
bspc rule -a sun-awt-X11-XDialogPeer state=floating
```
These are 2 terminal windows in tall layout (one is too small, highlighted on the left)

![image](https://user-images.githubusercontent.com/44126901/129238145-4cfdd222-ef27-4333-8238-331d48008ed6.png)

**Comment by totoroot** [comment]
There might be an issue with the package on NixOS then, since I ran into the same issue on NixOS 21.11...

**Comment by totoroot** [comment]
@addy419 @b4sqss I have actually found the issue with the NixOS package and am happy to report that [my fix got merged into nixpkgs](https://github.com/NixOS/nixpkgs/pull/171569/files) today. You should soon be able to install it from unstaged channel.

The affected layouts (tall, rtall, wide, rwide) did not work because, while `bc` was correctly packaged, it needed to be replaced in the layout scripts in the lib directory as well. Since the command `bc` was not found the correct ratio could not be calculated.

I also am now one of the package's maintainers so feel free to open up an issue in nixpkgs and ping me if it does not work as expected.

@phenax I believe this issue can be closed, as there is now a fix in nixpkgs and it wasn't `bsp-layout`'s issue in the first place.
Thanks for this package!
